### ISSUE TITLE
Product subcategories

### ISSUE THREAD

**Issue by thomasjthomasj** [mothership-ec/cog-mothership-commerce#242]
Mothership doesn't currently support subcategories, however, the Union site divides its products into categories and subcategories, for instance:

+ Strings & Things
    + Strings
    + Capos
    + Straps
+ Instruments
    + Guitars
    + Ukuleles

It would be good to be able to support subcategories as I can see this coming up in the future, but it may bring up more complications.

The Union site could potentially get away with creating top level CMS pages for Strings & Things etc. and using the bottom level categories as the product categories.

However, I think subcategories are something that future clients are probably going to want, and if we're gonna be breaking BC with <a href="https://github.com/messagedigital/cog-mothership-commerce/issues/238">this</a> anyway, it might be a good opportunity to implement it.

**Comment by kuiche** [comment]
Seems like this is resolved
