### ISSUE TITLE
Many areas that use products collapse under the pressure of loading hundreds/thousands of them

### ISSUE THREAD

**Issue by thomasjthomasj** [mothership-ec/cog-mothership-commerce#297]
Union has over 1000 products, and anywhere that loads all of them, such as the Products tab in the admin panel, or the Product field type when editing content, causes the site to time out. The best solution for this is probably to lazy load a lot of the properties of a product as is done in the Order object.

Unfortunately I can't find the commit where this happened

**Comment by kuiche** [comment]
Not really a problem anymore with Lazy Loading.
